spring:
  config.activate.on-profile: deploy
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  session:
    store-type: jdbc

  datasource:
    driver-class-name: org.mariadb.jdbc.Drvier

  mail:
    host: smtp.gmail.com
    port: 587
    username: PocketMarkDev@gmail.com
    password: ${gmailPw}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  

server:
  port: 9090


---
spring:
  config.activate.on-profile: default
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql : true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  mail:
    host: smtp.gmail.com
    port: 587
    username: PocketMarkDev@gmail.com
    password: ${gmailPw}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  

logging:
  level:
    org:
      # springframework.orm.jpa: DEBUG
      # springframework.transaction: DEBUG
      # springframework.transaction.interceptor: trace
      # hibernate:
      #   type:
      #     descriptor:
      #       sql: trace 

server:
  port: 9090

---
spring:
  config.activate.on-profile: ping9
  h2:
    console:
      enabled: true
  jpa:
    show-sql : true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  level:
    org:
      springframework.orm.jpa: DEBUG
      springframework.transaction: DEBUG
      # springframework.transaction.interceptor: trace
      hibernate:
        type:
          descriptor:
            sql: trace 

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true